src/java/controllerView/PublicacionController.java
package controllerView;

import model.Publicacion;
import controllerView.util.JsfUtil;
import controllerView.util.PaginationHelper;
import controller.PublicacionFacade;
import java.awt.event.ActionEvent;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpSession;
import model.Comentario;
import model.PublicacionHasTag;
import model.Tag;
import model.Usuario;
import org.primefaces.event.CloseEvent;

@Named("publicacionController")
@SessionScoped
public class PublicacionController implements Serializable {

    private Publicacion current;
    private DataModel items = null;
    @EJB
    private controller.PublicacionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private List<Publicacion> preguntasRecientes;
    private List<Publicacion> preguntasPuntuadas;
    private List<Publicacion> experienciasRecientes;
    private List<Publicacion> experienciasPuntuadas;
    private List<Publicacion> publicacionesEncontradas;
    private List<Publicacion> publicacionesUsuario;
    private List<Publicacion> publicacionesPreguntasRecientesVisto;
    private List<Publicacion> publicacionesPreguntasPuntuadasVisto;
    private List<Publicacion> publicacionesExperienciasRecientesVisto;
    private List<Publicacion> publicacionesExperienciasPuntuadasVisto;
    private String tag = "";
    private List<Tag> tagPublicacion = new ArrayList<Tag>();
    private Tag tagNuevo;
    private Publicacion publicacionVer;
    private Comentario comentarioPublicacion;

    public PublicacionController() {
    }

   
    
    
    public List<Publicacion> getPublicacionesPreguntasRecientesVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesPreguntasRecientesVisto = ejbFacade.cargarPreguntasRecientesUsuario(usuario);
        return publicacionesPreguntasRecientesVisto;
    }

    public List<Publicacion> getPublicacionesPreguntasPuntuadasVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesPreguntasPuntuadasVisto = ejbFacade.cargarPreguntasPuntuadasUsuario(usuario);
        return publicacionesPreguntasPuntuadasVisto;
    }

    public List<Publicacion> getPublicacionesExperienciasRecientesVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesExperienciasRecientesVisto = ejbFacade.cargarExperienciasRecientesUsuario(usuario);
        return publicacionesExperienciasRecientesVisto;
    }

    public List<Publicacion> getPublicacionesExperienciasPuntuadasVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesExperienciasPuntuadasVisto = ejbFacade.cargarExperienciasPuntuadasUsuario(usuario);
        return publicacionesExperienciasPuntuadasVisto;
    }
    
    public void agregarComentario(){
        this.comentarioPublicacion.setPublicacion(publicacionVer);
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario user = (Usuario) session.getAttribute("usuario");
        this.comentarioPublicacion.setUsuario(user);
        Date fecha= new Date();
        comentarioPublicacion.setFecha(fecha);
        this.ejbFacade.agregarComentario(comentarioPublicacion);
    
    }

    public Comentario getComentarioPublicacion() {
        return comentarioPublicacion;
    }

    public void setComentarioPublicacion(Comentario comentarioPublicacion) {
        this.comentarioPublicacion = comentarioPublicacion;
    }
    
    public List<Tag> getTagPublicacion() {
        return tagPublicacion;
    }

    public Tag getTagNuevo() {
        return tagNuevo;
    }

    public void setTagNuevo(Tag tagNuevo) {
        this.tagNuevo = tagNuevo;
    }

    public void setTagPublicacion(List<Tag> tagPublicacion) {
        this.tagPublicacion = tagPublicacion;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Publicacion getPublicacionVer() {
        return publicacionVer;
    }

    public void setPublicacionVer(Publicacion publicacionVer) {
        this.publicacionVer = publicacionVer;
    }

    @PostConstruct
    public void init() {
        this.tagNuevo = new Tag();
        this.current = new Publicacion();
        this.publicacionVer = new Publicacion();
        this.comentarioPublicacion=new Comentario();
    }

    public List<Publicacion> getPublicacionesUsuario() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario user = (Usuario) session.getAttribute("usuario");
        publicacionesUsuario = ejbFacade.listarPublicacionesUsuario(user);
        return publicacionesUsuario;
    }

    public void cargarPublicacionVer(Publicacion pub) {
        this.publicacionVer = pub;
        this.publicacionVer.setCalificacion(publicacionVer.getCalificacion()+1);
        this.ejbFacade.edit(publicacionVer);
    }

    public void setPublicacionesUsuario(List<Publicacion> publicacionesUsuario) {
        this.publicacionesUsuario = publicacionesUsuario;
    }

    public void limpiarBusqueda() {
        this.tag = "";
        this.publicacionesEncontradas = null;
    }

    public List<Publicacion> getPublicacionesEncontradas() {
        return publicacionesEncontradas;
    }

    public List<Tag> completeTags(String query) {
        List<Tag> allTags = ejbFacade.cargarTags();
        List<Tag> filteredTags = new ArrayList<>();
        
        for (int i = 0; i < allTags.size(); i++) {
            Tag tagSel = allTags.get(i);
            if (tagSel.getDescipcion().toLowerCase().startsWith(query)) {
                filteredTags.add(tagSel);
            }
        }
        return filteredTags;
    }

    /**
     * Perrmite Cargar un listado con todas las publicaciones de cualquier tipo
     * que esten asociadas al tag de busqueda, para su posterior visualizacion
     * en GUI
     */
    public void buscarPublicaciones() {
        this.publicacionesEncontradas = this.ejbFacade.buscarPublicaciones(tag);
    }

    public List<Publicacion> getPreguntasRecientes() {
        this.cargarPreguntasRecientes();
        return preguntasRecientes;
    }

    public List<Publicacion> getPreguntasPuntuadas() {
        this.cargarPreguntasPuntuadas();
        return preguntasPuntuadas;
    }

    public List<Publicacion> getExperienciasRecientes() {
        this.cargarExperienciasRecientes();
        return experienciasRecientes;
    }

    public List<Publicacion> getExperienciasPuntuadas() {
        this.cargarExperienciasPuntuadas();
        return experienciasPuntuadas;
    }

    /**
     * Metodo que carga las 20 publicaciones con mayor calificacion,para su
     * posterior visualizacion en GUI
     */
    private void cargarPreguntasPuntuadas() {
        preguntasPuntuadas = ejbFacade.cargarPreguntasPuntuadas();

    }

    public boolean nuevoTag() {
        this.ejbFacade.crearNuevoTag(tagNuevo);
        tagNuevo.setDescipcion("");
        return true;

    }

    public Publicacion getSelected() {
        if (current == null) {
            current = new Publicacion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PublicacionFacade getFacade() {
        return ejbFacade;
    }

    public boolean cargar() {
        return true;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Publicacion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Publicacion();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            return prepareCreate();

src/java/controllerView/TagController.java
package controllerView;

import model.Tag;
import controllerView.util.JsfUtil;
import controllerView.util.PaginationHelper;
import controller.TagFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("tagController")
@SessionScoped
public class TagController implements Serializable {

    private Tag current;
    private DataModel items = null;
    @EJB
    private controller.TagFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private TagControllerConverter tagConverter;

    public TagControllerConverter getTagConverter() {
        return tagConverter;
    }

    public void setTagConverter(TagControllerConverter tagConverter) {
        this.tagConverter = tagConverter;
    }

    @PostConstruct
    public void init() {
        this.tagConverter=new TagControllerConverter();

    }

    public TagController() {
    }

    public Tag getSelected() {
        if (current == null) {
            current = new Tag();
            selectedItemIndex = -1;
        }
        return current;
    }

    private TagFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Tag) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Tag();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TagCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Tag) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TagUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public void agregarTag() {
        this.create();
        this.current = null;
    }

    public String destroy() {
        current = (Tag) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TagDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Tag getTag(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    public List<Tag> getTags() {
        return ejbFacade.cargarTodo();
    }

    @FacesConverter(forClass = Tag.class)
    public static class TagControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TagController controller = (TagController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "tagController");
            return controller.getTag(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Tag) {
                Tag o = (Tag) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Tag.class.getName());
            }
        }

    }

}

web/publicacion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>

    </h:head>

    <h:body>
        <h:form>
            <h:panelGrid columns="2">

                <p:outputLabel value="#{bundle.CreatePublicacionLabel_tipo}" for="tipo" />
                <h:selectOneRadio id= "tipo"  value = "#{publicacionController.selected.tipo}" >
                <f:selectItem  itemLabel = "Pregunta"  itemValue = "Pregunta"  />
                <f:selectItem  itemLabel = "Experiencia"  itemValue = "Experiencia"  />
                </h:selectOneRadio >

                <p:outputLabel value="#{bundle.CreatePublicacionLabel_titulo}" for="titulo" />
                <p:inputText id="titulo" value="#{publicacionController.selected.titulo}" style="width:100%; "  />

                <p:outputLabel value="#{bundle.CreatePublicacionLabel_contenido}" for="contenido" />
                <p:inputTextarea rows="4" style="width:624px; height: 355px;" id="contenido" value="#{publicacionController.selected.contenido}" title="#{bundle.CreatePublicacionTitle_contenido}" />



                <p:outputLabel value="Tags Publicacion" for="tags" />
                <p:inputText id="tags" value="#{publicacionController.selected.contenido}" style="width:100%; "  />


                <p:outputLabel value="Nuevo Tag" for="tag" />
                <h:panelGrid columns="2">
                    <p:inputText id="tag" value="#{tagController.selected.descipcion}"  />
                    <p:commandButton value="AgregarTag"></p:commandButton>
                </h:panelGrid>

            </h:panelGrid>
            <br />
            <p:commandButton value="REGISTRAR" />
            <br />
            <br />

        </h:form>


    </h:body>
</html>

web/publicacion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPublicacionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_id}" for="id" />
                    <h:inputText id="id" value="#{publicacionController.selected.id}" title="#{bundle.EditPublicacionTitle_id}" required="true" requiredMessage="#{bundle.EditPublicacionRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_titulo}" for="titulo" />
                    <h:inputText id="titulo" value="#{publicacionController.selected.titulo}" title="#{bundle.EditPublicacionTitle_titulo}" />
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_fecha}" for="fecha" />
                    <h:inputText id="fecha" value="#{publicacionController.selected.fecha}" title="#{bundle.EditPublicacionTitle_fecha}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_contenido}" for="contenido" />
                    <h:inputTextarea rows="4" cols="30" id="contenido" value="#{publicacionController.selected.contenido}" title="#{bundle.EditPublicacionTitle_contenido}" />
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_tipo}" for="tipo" />
                    <h:inputText id="tipo" value="#{publicacionController.selected.tipo}" title="#{bundle.EditPublicacionTitle_tipo}" />
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_calificacion}" for="calificacion" />
                    <h:inputText id="calificacion" value="#{publicacionController.selected.calificacion}" title="#{bundle.EditPublicacionTitle_calificacion}" />
                    <h:outputLabel value="#{bundle.EditPublicacionLabel_usuario}" for="usuario" />
                    <h:selectOneMenu id="usuario" value="#{publicacionController.selected.usuario}" title="#{bundle.EditPublicacionTitle_usuario}" required="true" requiredMessage="#{bundle.EditPublicacionRequiredMessage_usuario}">
                        <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{publicacionController.update}" value="#{bundle.EditPublicacionSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPublicacionViewLink}"/>
                <br />
                <h:commandLink action="#{publicacionController.prepareList}" value="#{bundle.EditPublicacionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditPublicacionIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/publicacion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPublicacionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPublicacionEmpty}" rendered="#{publicacionController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{publicacionController.items.rowCount > 0}">
                    <h:outputText value="#{publicacionController.pagination.pageFirstItem + 1}..#{publicacionController.pagination.pageLastItem + 1}/#{publicacionController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{publicacionController.previous}" value="#{bundle.Previous} #{publicacionController.pagination.pageSize}" rendered="#{publicacionController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{publicacionController.next}" value="#{bundle.Next} #{publicacionController.pagination.pageSize}" rendered="#{publicacionController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{publicacionController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_titulo}"/>
                            </f:facet>
                            <h:outputText value="#{item.titulo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_fecha}"/>
                            </f:facet>
                            <h:outputText value="#{item.fecha}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_contenido}"/>
                            </f:facet>
                            <h:outputText value="#{item.contenido}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_tipo}"/>
                            </f:facet>
                            <h:outputText value="#{item.tipo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_calificacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.calificacion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPublicacionTitle_usuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.usuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{publicacionController.prepareView}" value="#{bundle.ListPublicacionViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{publicacionController.prepareEdit}" value="#{bundle.ListPublicacionEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{publicacionController.destroy}" value="#{bundle.ListPublicacionDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{publicacionController.prepareCreate}" value="#{bundle.ListPublicacionCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListPublicacionIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>