src/java/model/Usuario.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author SoftVargas
 */
@Entity
@Table(name = "usuario")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Usuario.findAll", query = "SELECT u FROM Usuario u"),
    @NamedQuery(name = "Usuario.logIn", query = "SELECT u FROM Usuario u WHERE u.codigo = :codigo AND u.password=:pass"),

    @NamedQuery(name = "Usuario.findByCodigo", query = "SELECT u FROM Usuario u WHERE u.codigo = :codigo"),
    @NamedQuery(name = "Usuario.findByNick", query = "SELECT u FROM Usuario u WHERE u.nick = :nick"),
    @NamedQuery(name = "Usuario.findByRutaImagen", query = "SELECT u FROM Usuario u WHERE u.rutaImagen = :rutaImagen"),
    @NamedQuery(name = "Usuario.findByNombre", query = "SELECT u FROM Usuario u WHERE u.nombre = :nombre"),
    @NamedQuery(name = "Usuario.findByPassword", query = "SELECT u FROM Usuario u WHERE u.password = :password"),
    @NamedQuery(name = "Usuario.findByCorreo", query = "SELECT u FROM Usuario u WHERE u.correo = :correo")})
public class Usuario implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 7)
    @Column(name = "codigo")
    private String codigo;
    @Size(max = 20)
    @Column(name = "nick")
    private String nick;
    @Size(max = 125)
    @Column(name = "ruta_imagen")
    private String rutaImagen;
    @Size(max = 125)
    @Column(name = "nombre")
    private String nombre;
    @Size(max = 32)
    @Column(name = "password")
    private String password;
    @Size(max = 125)
    @Column(name = "correo")
    private String correo;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "usuario")
    private List<Publicacion> publicacionList;
    @ManyToMany
    @JoinTable(
            name = "seguido_seguidor",
            joinColumns = {
                @JoinColumn(name = "seguidor", referencedColumnName = "codigo")},
            inverseJoinColumns = {
                @JoinColumn(name = "seguido", referencedColumnName = "codigo")})
    private List<Usuario> seguidoSeguidorList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "usuario")
    private List<Comentario> comentarioList;

    public Usuario() {
    }

    public Usuario(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getRutaImagen() {
        return rutaImagen;
    }

    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @XmlTransient
    public List<Publicacion> getPublicacionList() {
        return publicacionList;
    }

    public void setPublicacionList(List<Publicacion> publicacionList) {
        this.publicacionList = publicacionList;
    }

    @XmlTransient
    public List<Usuario> getSeguidoSeguidorList() {
        return seguidoSeguidorList;
    }

    public void setSeguidoSeguidorList(List<Usuario> seguidoSeguidorList) {
        this.seguidoSeguidorList = seguidoSeguidorList;
    }

    @XmlTransient
    public List<Comentario> getComentarioList() {
        return comentarioList;
    }

    public void setComentarioList(List<Comentario> comentarioList) {
        this.comentarioList = comentarioList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (codigo != null ? codigo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Usuario)) {
            return false;
        }
        Usuario other = (Usuario) object;
        if ((this.codigo == null && other.codigo != null) || (this.codigo != null && !this.codigo.equals(other.codigo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Modelo.Usuario[ codigo=" + codigo + " ]";
    }

}

src/java/controllerView/PublicacionController.java
package controllerView;

import model.Publicacion;
import controllerView.util.JsfUtil;
import controllerView.util.PaginationHelper;
import controller.PublicacionFacade;
import java.awt.event.ActionEvent;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpSession;
import model.Comentario;
import model.PublicacionHasTag;
import model.Tag;
import model.Usuario;
import org.primefaces.event.CloseEvent;

@Named("publicacionController")
@SessionScoped
public class PublicacionController implements Serializable {

    private Publicacion current;
    private DataModel items = null;
    @EJB
    private controller.PublicacionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    private List<Publicacion> preguntasRecientes;
    private List<Publicacion> preguntasPuntuadas;
    private List<Publicacion> experienciasRecientes;
    private List<Publicacion> experienciasPuntuadas;
    private List<Publicacion> publicacionesEncontradas;
    private List<Publicacion> publicacionesUsuario;
    private List<Publicacion> publicacionesPreguntasRecientesVisto;
    private List<Publicacion> publicacionesPreguntasPuntuadasVisto;
    private List<Publicacion> publicacionesExperienciasRecientesVisto;
    private List<Publicacion> publicacionesExperienciasPuntuadasVisto;
    private String tag = "";
    private List<Tag> tagPublicacion = new ArrayList<Tag>();
    private Tag tagNuevo;
    private Publicacion publicacionVer;
    private Comentario comentarioPublicacion;

    public PublicacionController() {
    }

   
    
    
    public List<Publicacion> getPublicacionesPreguntasRecientesVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesPreguntasRecientesVisto = ejbFacade.cargarPreguntasRecientesUsuario(usuario);
        return publicacionesPreguntasRecientesVisto;
    }

    public List<Publicacion> getPublicacionesPreguntasPuntuadasVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesPreguntasPuntuadasVisto = ejbFacade.cargarPreguntasPuntuadasUsuario(usuario);
        return publicacionesPreguntasPuntuadasVisto;
    }

    public List<Publicacion> getPublicacionesExperienciasRecientesVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesExperienciasRecientesVisto = ejbFacade.cargarExperienciasRecientesUsuario(usuario);
        return publicacionesExperienciasRecientesVisto;
    }

    public List<Publicacion> getPublicacionesExperienciasPuntuadasVisto() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario usuario = (Usuario) session.getAttribute("usuarioVisto");
        this.publicacionesExperienciasPuntuadasVisto = ejbFacade.cargarExperienciasPuntuadasUsuario(usuario);
        return publicacionesExperienciasPuntuadasVisto;
    }
    
    public void agregarComentario(){
        this.comentarioPublicacion.setPublicacion(publicacionVer);
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario user = (Usuario) session.getAttribute("usuario");
        this.comentarioPublicacion.setUsuario(user);
        Date fecha= new Date();
        comentarioPublicacion.setFecha(fecha);
        this.ejbFacade.agregarComentario(comentarioPublicacion);
    
    }

    public Comentario getComentarioPublicacion() {
        return comentarioPublicacion;
    }

    public void setComentarioPublicacion(Comentario comentarioPublicacion) {
        this.comentarioPublicacion = comentarioPublicacion;
    }
    
    public List<Tag> getTagPublicacion() {
        return tagPublicacion;
    }

    public Tag getTagNuevo() {
        return tagNuevo;
    }

    public void setTagNuevo(Tag tagNuevo) {
        this.tagNuevo = tagNuevo;
    }

    public void setTagPublicacion(List<Tag> tagPublicacion) {
        this.tagPublicacion = tagPublicacion;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Publicacion getPublicacionVer() {
        return publicacionVer;
    }

    public void setPublicacionVer(Publicacion publicacionVer) {
        this.publicacionVer = publicacionVer;
    }

    @PostConstruct
    public void init() {
        this.tagNuevo = new Tag();
        this.current = new Publicacion();
        this.publicacionVer = new Publicacion();
        this.comentarioPublicacion=new Comentario();
    }

    public List<Publicacion> getPublicacionesUsuario() {
        FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) context.getExternalContext().getSession(false);
        Usuario user = (Usuario) session.getAttribute("usuario");
        publicacionesUsuario = ejbFacade.listarPublicacionesUsuario(user);
        return publicacionesUsuario;
    }

    public void cargarPublicacionVer(Publicacion pub) {
        this.publicacionVer = pub;
        this.publicacionVer.setCalificacion(publicacionVer.getCalificacion()+1);
        this.ejbFacade.edit(publicacionVer);
    }

    public void setPublicacionesUsuario(List<Publicacion> publicacionesUsuario) {
        this.publicacionesUsuario = publicacionesUsuario;
    }

    public void limpiarBusqueda() {
        this.tag = "";
        this.publicacionesEncontradas = null;
    }

    public List<Publicacion> getPublicacionesEncontradas() {
        return publicacionesEncontradas;
    }

    public List<Tag> completeTags(String query) {
        List<Tag> allTags = ejbFacade.cargarTags();
        List<Tag> filteredTags = new ArrayList<>();
        
        for (int i = 0; i < allTags.size(); i++) {
            Tag tagSel = allTags.get(i);
            if (tagSel.getDescipcion().toLowerCase().startsWith(query)) {
                filteredTags.add(tagSel);
            }
        }
        return filteredTags;
    }

    /**
     * Perrmite Cargar un listado con todas las publicaciones de cualquier tipo
     * que esten asociadas al tag de busqueda, para su posterior visualizacion
     * en GUI
     */
    public void buscarPublicaciones() {
        this.publicacionesEncontradas = this.ejbFacade.buscarPublicaciones(tag);
    }

    public List<Publicacion> getPreguntasRecientes() {
        this.cargarPreguntasRecientes();
        return preguntasRecientes;
    }

    public List<Publicacion> getPreguntasPuntuadas() {
        this.cargarPreguntasPuntuadas();
        return preguntasPuntuadas;
    }

    public List<Publicacion> getExperienciasRecientes() {
        this.cargarExperienciasRecientes();
        return experienciasRecientes;
    }

    public List<Publicacion> getExperienciasPuntuadas() {
        this.cargarExperienciasPuntuadas();
        return experienciasPuntuadas;
    }

    /**
     * Metodo que carga las 20 publicaciones con mayor calificacion,para su
     * posterior visualizacion en GUI
     */
    private void cargarPreguntasPuntuadas() {
        preguntasPuntuadas = ejbFacade.cargarPreguntasPuntuadas();

    }

    public boolean nuevoTag() {
        this.ejbFacade.crearNuevoTag(tagNuevo);
        tagNuevo.setDescipcion("");
        return true;

    }

    public Publicacion getSelected() {
        if (current == null) {
            current = new Publicacion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PublicacionFacade getFacade() {
        return ejbFacade;
    }

    public boolean cargar() {
        return true;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Publicacion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Publicacion();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            return prepareCreate();

web/usuario/registro.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <script type="text/javascript" src="resources/scripts/jquery.js"></script>
                <script type="text/javascript" src="resources/scripts/funcionesCarga.js"></script>



                <title>Foro IS</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

               <p:layoutUnit position="north" size="180" >
                    <center>
                        <div style="width:70%; height:90%;">
                            <img  style="width:100%; height:155px;" src="../resources/imagenes/bannerA.png" alt=""/>
                        </div>
                    </center>
                </p:layoutUnit>




                <p:layoutUnit position="south" size="40" closable="false" collapsible="false" style="background: #b2d5d6;">
                    <center>
                        <h>Copyrigth Ingenieria de Sistemas - UFPS - 2015</h>
                    </center>
                </p:layoutUnit>

                <p:layoutUnit position="center" style="font-size: medium;">
                    <br/>
                   
                        <center>
                            <p:panel header="Registro de Usuario" >
                                <p:scrollPanel style="width:90%; height:360px">
                                       <h:form>
                                   

                                    <h:panelGrid id="grid" columns="2" cellpadding="8">


                                        <h:outputLabel for="nick" value="Nombre de Usuario:" style="font-weight:bold"/>                    
                                        <p:inputText id="nick" value="#{usuarioController.selected.nick}" title="#{bundle.CreateUsuarioTitle_nick}" required="true"  style="width: 300px"/>
                                      

                                      

                                        <h:outputLabel for="nombre" value="Nombre:" style="font-weight:bold"/>                    
                                        <p:inputText id="nombre" value="#{usuarioController.selected.nombre}" title="#{bundle.CreateUsuarioTitle_nombre}" required="true" style="width: 300px"/>
                                      
                                     

                                        <h:outputLabel for="codigo" value="Codigo:" style="font-weight:bold"/>                    
                                        <p:inputText id="codigo"  value="#{usuarioController.selected.codigo}" title="#{bundle.CreateUsuarioTitle_codigo}" required="true" style="width: 300px" requiredMessage="#{bundle.CreateUsuarioRequiredMessage_codigo}"/>
                                
                                  
                                        <h:outputLabel value="Contraseña:" for="password" style="font-weight:bold"/>
                                        <p:password id="password" value="#{usuarioController.selected.password}" feedback="true" required="true" style="width: 300px"/>                                        
                                  
                                        
                                        <h:outputLabel value="Confirme su Contraseña:" for="password2" style="font-weight:bold"/>
                                        <p:password id="password2" feedback="true" required="true" style="width: 300px"/>                                        
                 
                                        
                                        <h:outputLabel for="correo" value="E-Mail:" style="font-weight:bold"/>
                                        <p:inputText id="correo" value="#{usuarioController.selected.correo}" style="width: 300px" title="#{bundle.CreateUsuarioTitle_correo}"/>
                                 
                                        
                                        

                                    </h:panelGrid>
                                    <br/>
                                    <p:commandButton value="REGISTRAR"  icon="ui-icon-check"  action="#{usuarioController.registro()}" />
                                       </h:form>
                                </p:scrollPanel>
                            </p:panel>
                        </center>
              

                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>